FROM node:lts-alpine3.19 AS base

USER root

# Install pnpm
RUN npm install -g pnpm

# Set the working directory
WORKDIR /app

# Copy the package.json and pnpm-lock.yaml files
COPY package.json pnpm-lock.yaml ./

# Install the dependencies
RUN pnpm install --no-optional --frozen-lockfile

# Copy the source app
ADD . ./

# Tell Node.js that we are in production mode
ENV NODE_ENV=production

# Build the application
RUN pnpm compile

# Start the application
CMD ["pnpm", "start"]
